name: Validate Dockerfile

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t sudoku-solver-backend .

      - name: Run Docker Container
        run: docker run -d --rm -p 8000:8000 sudoku-solver-backend

      - name: Test API Container
        run: |
          sleep 5 # Give the container some time to start
          curl -f http://localhost:8000/docs

      - name: Stop and Remove Container
        run: docker stop sudoku-solver-backend-container
